commerce_payment.commerce_payment_gateway.plugin.btcpay:
  type: commerce_payment_gateway_configuration
  mapping:
    pairing_code_livenet:
      type: string
      label: "Livenet pairing code"
    pairing_code_testnet:
      type: string
      label: "Testnet pairing code"
    server_livenet:
      type: string
      label: "Livenet server URL"
    server_testnet:
      type: string
      label: "Testnet server URL"
